version: "2"
plugins:
  golint:
    enabled: true
  gofmt:
    enabled: true
  govet:
    enabled: true
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.go"
  - "**.md"
exclude_paths:
- "**/vendor/**/*"
- "**/*_test.go"
