version: 2.0
jobs:
  build:
    docker:
      - image: circleci/golang:1

    working_directory: /go/src/github.com/palsivertsen/goutils
    steps:
      - checkout
      - run:
          name: Download reporting tool
          command: |
            curl -o ./cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 -L
            chmod u+x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: Dependencies
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
      - run:
          name: Code coverage
          command: |
            go test -coverprofile=c.out ./...
            ./cc-test-reporter after-build -t gocov --exit-code $?
